import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/Header";
import PromptInput from "@/components/PromptInput";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ai Image Generater",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* header */}
        <Header />

        {/* prompt input */}
        <PromptInput />

        {/* main */}
        {children}
      </body>
    </html>
  );
}
